development:
  adapter: mysql2
  database: promo_site_development
  username: root
  password: "1234"

test:
  adapter: mysql2
  database: promo_site_test
  username: root
  password: "1234"

production:
  host: ec2-54-243-190-226.compute-1.amazonaws.com
  adapter: postgresql
  database: ddh2h7ighel9u5
  username: ffjmslhfrpopbi
  password: "N3BWnEM4H8X6uI1kvxO8-3qsKM"
  port: 5432