development:
  adapter: mysql2
  database: promo_site_development
  username: root
  password: "1234"

test:
  adapter: mysql2
  database: promo_site_test
  username: root
  password: "1234"

production:
  host: ec2-54-235-242-31.compute-1.amazonaws.com
  adapter: postgresql
  database: dujjh3lb152jj
  username: ahahzfjkhgdltc
  password: "w1e-i54eGFtAHDAwIckXaCoqTl"
  port: 5432